version: '3'

services:
  paper-collector:
    build: .
    container_name: paper-collector
    volumes:
      # 将收集的论文保存到本地目录
      - ./data/collected-articles:/app/data/collected-articles
      # 将日志文件保存到本地
      - ./logs:/app/logs
      # 将数据库文件保存到本地
      - ./data:/app/data
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      # 邮件配置
      - SENDER_EMAIL=${SENDER_EMAIL}
      - PAPER_COLLECTOR_PASSWORD=${PAPER_COLLECTOR_PASSWORD}
      # SMTP配置
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USE_SSL=${SMTP_USE_SSL}
      # Flask配置
      - SECRET_KEY=${SECRET_KEY:-dev-key-please-change-in-production}
      - FLASK_ENV=${FLASK_ENV:-production}
      # 数据库配置
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/paper_collector.db}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # 定时服务，使用cron定时执行
  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    container_name: paper-collector-cron
    depends_on:
      - paper-collector
    volumes:
      # 确保与主服务使用相同的数据卷
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      # 邮件配置
      - SENDER_EMAIL=${SENDER_EMAIL}
      - PAPER_COLLECTOR_PASSWORD=${PAPER_COLLECTOR_PASSWORD}
      # SMTP配置
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USE_SSL=${SMTP_USE_SSL}
      # Flask配置
      - SECRET_KEY=${SECRET_KEY:-dev-key-please-change-in-production}
      # 数据库配置
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/paper_collector.db}
    restart: unless-stopped 